name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: soo6ya

          template: classic

          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Kolkata

          # Contribution calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Most used programming languages
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%

          # Coding habits
          plugin_habits: yes
          plugin_habits_from: 100

          # GitHub Projects
          plugin_projects: yes
          plugin_projects_descriptions: yes

          # Repository topics
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15

          # Output file
          filename: github-metrics.svg
